### ISSUE TITLE
update tournament pack

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#19]
two version, availb @ rip.ddrillini.club

**Comment by ianklatzco** [comment]
done, but now pls
`mv RIP10-no-difficulty-prefixes RIP (No Difficulties)`

**Comment by andrewipark** [comment]
oh right, because SM5 still doesn't have a groups definition and still reads them off the folder name _sigh_
